import type { BuyerListing } from "@/components/buyer/types";

/** Mock published listings around central London until the API is ready. */
export const MOCK_BUYER_LISTINGS: BuyerListing[] = [
  {
    id: "lst-shoreditch-billboard",
    title: "Shoreditch High Street Billboard",
    description:
      "Premium roadside digital board facing inbound traffic on Shoreditch High Street. High footfall evening and weekend coverage.",
    category: "billboard",
    city: "London",
    postcode: "E1 6QL",
    addressLine1: "214 Shoreditch High St",
    lat: 51.5238,
    lng: -0.0772,
    pricePerDayPence: 4500,
    cisScore: 94,
    audienceSize: 28000,
    audienceTags: ["Commuters", "Shoppers"],
    bookingType: "instant",
    availability: "available",
    imageUrls: [],
  },
  {
    id: "lst-hackney-gym",
    title: "Hackney Wick Gym Wall",
    description:
      "Interior feature wall beside reception and changing rooms. Ideal for fitness and wellness brands.",
    category: "gym",
    city: "London",
    postcode: "E9 5EN",
    addressLine1: "12 White Post Ln",
    lat: 51.5441,
    lng: -0.0234,
    pricePerDayPence: 1800,
    cisScore: 81,
    audienceSize: 4200,
    audienceTags: ["Fitness", "Locals"],
    bookingType: "instant",
    availability: "available",
    imageUrls: [],
  },
  {
    id: "lst-islington-cafe",
    title: "Upper Street Café Screens",
    description:
      "Twin digital menu screens with reserved ad slots during peak brunch hours.",
    category: "cafe",
    city: "London",
    postcode: "N1 2UD",
    addressLine1: "88 Upper St",
    lat: 51.5382,
    lng: -0.1031,
    pricePerDayPence: 950,
    cisScore: null,
    audienceSize: 1600,
    audienceTags: ["Locals", "Shoppers"],
    bookingType: "request",
    availability: "limited",
    imageUrls: [],
  },
  {
    id: "lst-canary-wharf-shop",
    title: "Canary Wharf Window Takeover",
    description:
      "Full window wrap on retail unit facing Jubilee Place concourse.",
    category: "shop",
    city: "London",
    postcode: "E14 5AB",
    addressLine1: "15 Jubilee Place",
    lat: 51.5054,
    lng: -0.0235,
    pricePerDayPence: 6200,
    cisScore: 72,
    audienceSize: 35000,
    audienceTags: ["Commuters", "Professionals"],
    bookingType: "instant",
    availability: "booked",
    imageUrls: [],
  },
  {
    id: "lst-bethnal-sports",
    title: "Bethnal Green Sports Club Boards",
    description:
      "Pitch-side boards for weekend league matches and midweek training sessions.",
    category: "sports_club",
    city: "London",
    postcode: "E2 0AA",
    addressLine1: "Paradise Row",
    lat: 51.5274,
    lng: -0.0552,
    pricePerDayPence: 1200,
    cisScore: 88,
    audienceSize: 900,
    audienceTags: ["Families", "Locals"],
    bookingType: "request",
    availability: "available",
    imageUrls: [],
  },
  {
    id: "lst-southbank-venue",
    title: "Southbank Event Venue Foyer",
    description:
      "Digital totem in the main foyer during ticketed evening events.",
    category: "event_venue",
    city: "London",
    postcode: "SE1 8XX",
    addressLine1: "Belvedere Rd",
    lat: 51.5066,
    lng: -0.1167,
    pricePerDayPence: 3800,
    cisScore: 55,
    audienceSize: 12000,
    audienceTags: ["Culture", "Tourists"],
    bookingType: "instant",
    availability: "limited",
    imageUrls: [],
  },
  {
    id: "lst-camden-school",
    title: "Camden Community School Hall",
    description:
      "Banner placements at term-time assemblies and community open evenings.",
    category: "school",
    city: "London",
    postcode: "NW1 8AB",
    addressLine1: "Chalk Farm Rd",
    lat: 51.5412,
    lng: -0.1465,
    pricePerDayPence: 700,
    cisScore: null,
    audienceSize: 1100,
    audienceTags: ["Families", "Locals"],
    bookingType: "request",
    availability: "available",
    imageUrls: [],
  },
  {
    id: "lst-greenwich-festival",
    title: "Greenwich Summer Festival Stall",
    description:
      "Branded stall footprint plus PA mention during weekend festival programme.",
    category: "festival",
    city: "London",
    postcode: "SE10 9NN",
    addressLine1: "Cutty Sark Gardens",
    lat: 51.4826,
    lng: -0.0097,
    pricePerDayPence: 2500,
    cisScore: 66,
    audienceSize: 18000,
    audienceTags: ["Families", "Tourists"],
    bookingType: "instant",
    availability: "limited",
    imageUrls: [],
  },
];

export function getMockListingById(id: string): BuyerListing | undefined {
  return MOCK_BUYER_LISTINGS.find((listing) => listing.id === id);
}
